app/cookies/models.py
from app.extensions.database import db, CRUDMixin

class Cookie(db.Model, CRUDMixin):
  id = db.Column(db.Integer, primary_key=True)
  slug = db.Column(db.String(80), unique=True)
  name = db.Column(db.String(80))
  price = db.Column(db.Numeric(10, 2))
  cookie_orders = db.relationship('CookieOrder', backref='cookie', lazy=True)

app/orders/models.py
from app.extensions.database import db, CRUDMixin

from datetime import datetime

class CookieOrder(db.Model, CRUDMixin):
  cookie_id = db.Column(db.Integer, db.ForeignKey('cookie.id'), primary_key=True)
  order_id = db.Column(db.Integer, db.ForeignKey('order.id'), primary_key=True)
  number_of_cookies = db.Column(db.Integer)


class Order(db.Model, CRUDMixin):
  id = db.Column(db.Integer, primary_key=True)
  date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  address = db.relationship('Address', backref='order', uselist=False, lazy=True)
  cookie_orders = db.relationship('CookieOrder', backref='order', lazy=True)
  
  
class Address(db.Model, CRUDMixin):
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(80))
  street = db.Column(db.String(80))
  city = db.Column(db.String(80))
  state = db.Column(db.String(80))
  zip = db.Column(db.String(80))
  country = db.Column(db.String(80))
  order_id = db.Column(db.Integer, db.ForeignKey('order.id'))
  

app/users/models.py
from app.extensions.database import db, CRUDMixin
from flask_login import UserMixin

class User(db.Model, CRUDMixin, UserMixin):
  id = db.Column(db.Integer, primary_key = True)
  email = db.Column(db.String(128), index = True, unique = True)
  password = db.Column(db.String(1024))

app/api/__init__.py
from . import routes

app/api/routes.py
from flask import Blueprint, jsonify, request
from .services.serialize_orders import serialize_orders
from ..orders.models import Order
from os import environ

blueprint = Blueprint('api', __name__)

@blueprint.get('/api/v1/orders')
def orders():
  if environ.get('API_KEY') == request.headers.get('X-API-KEY'):
    orders = Order.query.all()
    return jsonify(
      serialize_orders(orders)
    )
  else:
    return jsonify({'error': 'Invalid API key'}), 401

app/app.py
from flask import Flask
from . import cookies, simple_pages, orders, api, users
from app.extensions.database import db, migrate
from app.extensions.authentication import login_manager


def create_app():
  app = Flask(__name__)
  app.config.from_object('app.config')

  register_extensions(app)
  register_blueprints(app)

  return app

# Blueprints
def register_blueprints(app: Flask):
  app.register_blueprint(cookies.routes.blueprint)
  app.register_blueprint(simple_pages.routes.blueprint)
  app.register_blueprint(orders.routes.blueprint)
  app.register_blueprint(api.routes.blueprint)
  app.register_blueprint(users.routes.blueprint)
  
#Extentions  
def register_extensions(app: Flask):
  db.init_app(app)
  migrate.init_app(app, db, compare_type=True)
  login_manager.init_app(app)

app/cookies/__init__.py
from . import routes, models

app/cookies/routes.py
from flask import Blueprint, render_template, request, current_app
from .models import Cookie
from app.orders.models import Order

blueprint = Blueprint('cookies', __name__)


@blueprint.route('/cookies/<slug>')
def cookie(slug):
  cookie = Cookie.query.filter_by(slug=slug).first_or_404()
  return render_template('cookies/show.html', cookie=cookie)

@blueprint.route('/cookies')
def cookies():
  page = request.args.get('page', 1, type=int)
  cookies_pagination = Cookie.query.paginate(page=page, per_page=current_app.config['COOKIES_PER_PAGE'])
  return render_template('cookies/index.html', cookies_pagination=cookies_pagination)


@blueprint.route('/view-orders')
def preview():
  orders=Order.query.all()
  return render_template('preview.html',orders=orders)

@blueprint.route('/run-seed')
def run_seed():
  if not Cookie.query.filter_by(slug='chocolate-chip').first():
    import app.scripts.seed
    return 'Database seed completed!'
  else:
    return 'Nothing to run.'

app/orders/__init__.py
from . import models, routes

app/orders/routes.py
from flask import Blueprint, render_template, request, current_app
from app.cookies.models import Cookie
from .services.create_order import create_order
from flask_login import login_required


blueprint = Blueprint('orders', __name__)

@blueprint.get('/checkout')
@login_required
def get_checkout():
  cookies = Cookie.query.all()
  return render_template('orders/new.html', cookies=cookies)

@blueprint.post('/checkout')
def post_checkout():
  try:
    cookies = Cookie.query.all()

    if not all([
      request.form.get('name'),
      request.form.get('street'),
      request.form.get('city'),
      request.form.get('state'),
      request.form.get('zip'),
      request.form.get('country')
    ]):
      raise Exception('Please fill out all address fields.')

    create_order(request.form, cookies)
    return render_template('orders/new.html', cookies=cookies)

  except Exception as error_message:
    error = error_message or 'An error occurred while processing your order. Please make sure to enter valid data.'

    current_app.logger.info(f'Error creating an order: {error}')

    return render_template('orders/new.html', 
      cookies=cookies,
      error=error
    )

app/simple_pages/__init__.py
from . import routes

app/simple_pages/routes.py
from flask import Blueprint, render_template, redirect, url_for, send_file

blueprint = Blueprint('simple_pages', __name__)

@blueprint.route('/')
def index():
  name = 'Sam'
  fake_number = 342
  return render_template('index.html', name=name, visitor_number=fake_number)

@blueprint.route('/about')
def about():
  return 'I like cookies'

#example of a redirect
@blueprint.route('/about-me')
def about_me():
  return redirect(url_for('about'))

#Download route
#as atachment parameter triggers download
@blueprint.route('/legal')
def legal():
  return send_file('static/downloads/legal.txt', as_attachment=True)

app/users/__init__.py
from . import routes, models

app/users/routes.py
from flask import Blueprint, render_template, request, url_for, redirect
from app.users.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user

blueprint = Blueprint('users', __name__)

@blueprint.get('/register')
def get_register():
  return render_template('users/register.html')

@blueprint.post('/register')
def post_register():
  try:
    if request.form.get('password') != request.form.get('password_confirmation'):
      raise Exception('The password confirmation must match the password.')
    elif User.query.filter_by(email=request.form.get('email')).first():
      raise Exception('The email address is already registered.')

    user = User(
      email=request.form.get('email'),
      password=generate_password_hash(request.form.get('password'))
    )
    user.save()
    
    login_user(user)
    return redirect(url_for('cookies.cookies'))

  except Exception as error_message:
    error = error_message or 'An error occurred while creating a user. Please make sure to enter valid data.'
    return render_template('users/register.html', error=error)


@blueprint.get('/login')
def get_login():
  return render_template('users/login.html')

@blueprint.post('/login')
def post_login():
  try:
    user = User.query.filter_by(email=request.form.get('email')).first()

    if not user:
      raise Exception('No user with the given email address was found.')
    elif not check_password_hash(user.password, request.form.get('password')):
      raise Exception('The password does not appear to be correct.')
    
    login_user(user)
    return redirect(url_for('cookies.cookies'))
    
  except Exception as error_message:
    error = error_message or 'An error occurred while logging in. Please verify your email and password.'
    
    return render_template('users/login.html', error=error)


@blueprint.get('/logout')
def logout():
  logout_user()

  return redirect(url_for('users.get_login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <title>{% block title %}{% endblock %}</title>
  {% endblock %}
</head>
<body>
  {% block body %}{% endblock %}
</body>
<footer>
  <hr>
  {% if current_user.is_authenticated %}
    <small>
      Logged in as {{ current_user.email }}.
      <a href="{{ url_for('users.logout') }}">Logout</a>
    </small>
  {% endif %}
</footer>
</html>

app/templates/cookies/index.html
{% extends 'base.html' %}

{% block title %}Cookieshop{% endblock %}

{% block body %}
  <h1>Cookies</h1>
  <ul>
    {% for cookie in cookies_pagination.items %}

      <li>
        {% if cookie.price == 0.25 %}
          <s>{{ cookie.name }}</s>
        {% else %}
          <a href="/cookies/{{ cookie.slug }}">{{ cookie.name }}</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  <nav>
    {% if cookies_pagination.prev_num %}
      <a href="{{ url_for('cookies.cookies', page=cookies_pagination.prev_num) }}">Previous Page</a>
    {% else %}
      <span>Previous Page</span>
    {% endif %}
    <span> - </span>
    {% if cookies_pagination.next_num %}
      <a href="{{ url_for('cookies.cookies', page=cookies_pagination.next_num) }}">Next Page</a>
    {% else %}
      <span>Next Page</span>
    {% endif %}
  </nav>
{% endblock %}

        

app/templates/cookies/show.html
{% extends 'base.html' %}

{% block title %}Cookieshop{% endblock %}

{% block body %}
  <h1>{{cookie.name}}</h1>

  <p>Price: ${{cookie.price}}</p>

  <footer>
    <a href="/cookies">Back to all cookies</a>
  </footer>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block body %}

    <h1>Hello {{name}}!</h1>
  
    <p>You are visitor number {{visitor_number}}!</p>
    <a href="/cookies">Cookies</a>
    <br>

    <a href="/legal">Download legal details</a>

    <a href="/view-orders">Preview of orders</a>
    
{% endblock %}

app/templates/orders/new.html
{% extends 'base.html' %}

{% block title %}Cookieshop | Checkout{% endblock %}

{% block body %}
  <h1>Checkout</h1>

  <form method ="POST">

    <h2>Your Order:</h2>
    <ul>
      {% for cookie in cookies %}
        <li>
          <label for="cookie_{{ cookie.id }}">{{ cookie.name }}</label>
          <input type="number" name="{{ cookie.slug }}" id="cookie_{{ cookie.id }}" min="0" value="0">
        </li>
      {% endfor %}
    </ul>
    
    <h2>Your Address:</h2>
    <div>
      <label for="name">Full Name</label>
      <input type="text" name="name" id="name" placeholder="Jane Cookielover">
    </div>
    <div>
      <label for="street">Street and Number:</label>
      <input type="text" name="street" id="street" placeholder="Sample Street 24">
    </div>
    <div>
      <label for="city">City:</label>
      <input type="text" name="city" id="city" placeholder="Best Town">
    </div>
    <div>
      <label for="state">State:</label>
      <input type="text" name="state" id="state" placeholder="Bakerstate">
    </div>
    <div>
      <label for="zip">Zip:</label>
      <input type="text" name="zip" id="zip" placeholder="12345">
    </div>
    <div>
      <label for="country">Country:</label>
      <input type="text" name="country" id="country" placeholder="Cookieland">
    </div>
    
    <input type="submit" value="Submit Order">

  </form>
  {% if error %}
    <p style="color: tomato;">{{ error }}</p>
  {% endif %}
  
{% endblock %}

app/templates/preview.html
{% extends 'base.html' %}

{% block title %}Orders{% endblock %}

{% block body %}

    <h1>Orders</h1>

    <ul>
        {% for order in orders %}
          <li>
            <h3>Date: {{ order.date }} Address: {{ order.address.name }}</h3>
          </li>
        {% endfor %}
      </ul>

      <p style="color:red">Still in construction</p>
    
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Cookieshop | Login{% endblock %}

{% block body %}
  <h1>Login</h1>

  <form method="POST">
    <div>
      <label for="email">Email</label>
      <input type="email" name="email" id="email" required>
    </div>

    <div>
      <label for="password">Password</label>
      <input type="password" name="password" id="password" required>
    </div>
    
    <input type="submit" value="Login">
  </form>  
  {% if error %}
    <p style="color: tomato;">{{ error }}</p>
  {% endif %}
{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Cookieshop | Register{% endblock %}

{% block body %}
  <h1>Register</h1>

  <form method="POST">
    <div>
      <label for="email">Email</label>
      <input type="email" name="email" id="email" required>
    </div>

    <div>
      <label for="password">Password</label>
      <input type="password" name="password" id="password" required>
    </div>

    <div>
      <label for="password_confirmation">Password Confirmation</label>
      <input type="password" name="password_confirmation" id="password_confirmation" required>
    </div>
    
    <input type="submit" value="Sign Up">
  </form>  
  {% if error %}
    <p style="color: tomato;">{{ error }}</p>
  {% endif %}
{% endblock %}